CREATE TABLE CUSTOMER (
	ID BIGINT NOT NULL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE TARGET_CUSTOMER (
	CUSTOMER_ID BIGINT NOT NULL PRIMARY KEY
);

INSERT INTO CUSTOMER VALUES (1, 'human1', TRUE);
INSERT INTO CUSTOMER VALUES (2, 'human2', TRUE);
INSERT INTO CUSTOMER VALUES (3, 'human3', TRUE);
INSERT INTO CUSTOMER VALUES (4, 'human4', TRUE);
INSERT INTO CUSTOMER VALUES (5, 'human5', TRUE);
INSERT INTO CUSTOMER VALUES (6, 'human6', TRUE);
INSERT INTO CUSTOMER VALUES (7, 'human7', TRUE);
INSERT INTO CUSTOMER VALUES (8, 'human8', TRUE);
INSERT INTO CUSTOMER VALUES (9, 'human9', TRUE);
INSERT INTO CUSTOMER VALUES (10, 'human10', TRUE);
INSERT INTO CUSTOMER VALUES (11, 'human11', TRUE);
INSERT INTO CUSTOMER VALUES (12, 'human12', TRUE);
INSERT INTO CUSTOMER VALUES (13, 'human13', TRUE);
INSERT INTO CUSTOMER VALUES (14, 'human14', TRUE);

INSERT INTO CUSTOMER VALUES (101, 'non-human1', FALSE);
INSERT INTO CUSTOMER VALUES (102, 'non-human2', FALSE);
INSERT INTO CUSTOMER VALUES (103, 'non-human3', FALSE);
