spring:
  application:
    name: spring-batch-failover-kotlin
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console # enable h2 console


server:
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
